spring.application.name=CustomMQ
server.port=8090

# PostgreSQL konekcija
spring.datasource.url=jdbc:postgresql://localhost:5432/message_db

spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop